# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import room_pb2 as room__pb2


class RoomStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RoomTalk = channel.stream_stream(
        '/roomprotocol.Room/RoomTalk',
        request_serializer=room__pb2.RoomUpdate.SerializeToString,
        response_deserializer=room__pb2.RoomUpdate.FromString,
        )


class RoomServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RoomTalk(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RoomServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RoomTalk': grpc.stream_stream_rpc_method_handler(
          servicer.RoomTalk,
          request_deserializer=room__pb2.RoomUpdate.FromString,
          response_serializer=room__pb2.RoomUpdate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'roomprotocol.Room', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
