# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='room.proto',
  package='roomprotocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nroom.proto\x12\x0croomprotocol\"a\n\nUpdatePart\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08\x66loatVal\x18\x02 \x01(\x02\x12\x0e\n\x06intVal\x18\x03 \x01(\x05\x12\x11\n\tstringVal\x18\x04 \x01(\t\x12\x10\n\x08\x62ytesVal\x18\x05 \x01(\x0c\"D\n\nRoomUpdate\x12\x0c\n\x04type\x18\x01 \x01(\t\x12(\n\x06tokens\x18\x02 \x03(\x0b\x32\x18.roomprotocol.UpdatePart2L\n\x04Room\x12\x44\n\x08RoomTalk\x12\x18.roomprotocol.RoomUpdate\x1a\x18.roomprotocol.RoomUpdate\"\x00(\x01\x30\x01\x62\x06proto3')
)




_UPDATEPART = _descriptor.Descriptor(
  name='UpdatePart',
  full_name='roomprotocol.UpdatePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='roomprotocol.UpdatePart.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floatVal', full_name='roomprotocol.UpdatePart.floatVal', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intVal', full_name='roomprotocol.UpdatePart.intVal', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringVal', full_name='roomprotocol.UpdatePart.stringVal', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytesVal', full_name='roomprotocol.UpdatePart.bytesVal', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=125,
)


_ROOMUPDATE = _descriptor.Descriptor(
  name='RoomUpdate',
  full_name='roomprotocol.RoomUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='roomprotocol.RoomUpdate.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='roomprotocol.RoomUpdate.tokens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=195,
)

_ROOMUPDATE.fields_by_name['tokens'].message_type = _UPDATEPART
DESCRIPTOR.message_types_by_name['UpdatePart'] = _UPDATEPART
DESCRIPTOR.message_types_by_name['RoomUpdate'] = _ROOMUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdatePart = _reflection.GeneratedProtocolMessageType('UpdatePart', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEPART,
  __module__ = 'room_pb2'
  # @@protoc_insertion_point(class_scope:roomprotocol.UpdatePart)
  ))
_sym_db.RegisterMessage(UpdatePart)

RoomUpdate = _reflection.GeneratedProtocolMessageType('RoomUpdate', (_message.Message,), dict(
  DESCRIPTOR = _ROOMUPDATE,
  __module__ = 'room_pb2'
  # @@protoc_insertion_point(class_scope:roomprotocol.RoomUpdate)
  ))
_sym_db.RegisterMessage(RoomUpdate)



_ROOM = _descriptor.ServiceDescriptor(
  name='Room',
  full_name='roomprotocol.Room',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=197,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='RoomTalk',
    full_name='roomprotocol.Room.RoomTalk',
    index=0,
    containing_service=None,
    input_type=_ROOMUPDATE,
    output_type=_ROOMUPDATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROOM)

DESCRIPTOR.services_by_name['Room'] = _ROOM

# @@protoc_insertion_point(module_scope)
