// Code generated by capnpc-go. DO NOT EDIT.

package roompupdate

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type RoomUpdates struct{ capnp.Struct }

// RoomUpdates_TypeID is the unique identifier for the type RoomUpdates.
const RoomUpdates_TypeID = 0xfb039068971e1e29

func NewRoomUpdates(s *capnp.Segment) (RoomUpdates, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RoomUpdates{st}, err
}

func NewRootRoomUpdates(s *capnp.Segment) (RoomUpdates, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RoomUpdates{st}, err
}

func ReadRootRoomUpdates(msg *capnp.Message) (RoomUpdates, error) {
	root, err := msg.RootPtr()
	return RoomUpdates{root.Struct()}, err
}

func (s RoomUpdates) String() string {
	str, _ := text.Marshal(0xfb039068971e1e29, s.Struct)
	return str
}

func (s RoomUpdates) Updates() (RoomUpdates_RoomUpdate_List, error) {
	p, err := s.Struct.Ptr(0)
	return RoomUpdates_RoomUpdate_List{List: p.List()}, err
}

func (s RoomUpdates) HasUpdates() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s RoomUpdates) SetUpdates(v RoomUpdates_RoomUpdate_List) error {
	return s.Struct.SetPtr(0, v.List.ToPtr())
}

// NewUpdates sets the updates field to a newly
// allocated RoomUpdates_RoomUpdate_List, preferring placement in s's segment.
func (s RoomUpdates) NewUpdates(n int32) (RoomUpdates_RoomUpdate_List, error) {
	l, err := NewRoomUpdates_RoomUpdate_List(s.Struct.Segment(), n)
	if err != nil {
		return RoomUpdates_RoomUpdate_List{}, err
	}
	err = s.Struct.SetPtr(0, l.List.ToPtr())
	return l, err
}

// RoomUpdates_List is a list of RoomUpdates.
type RoomUpdates_List struct{ capnp.List }

// NewRoomUpdates creates a new list of RoomUpdates.
func NewRoomUpdates_List(s *capnp.Segment, sz int32) (RoomUpdates_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return RoomUpdates_List{l}, err
}

func (s RoomUpdates_List) At(i int) RoomUpdates { return RoomUpdates{s.List.Struct(i)} }

func (s RoomUpdates_List) Set(i int, v RoomUpdates) error { return s.List.SetStruct(i, v.Struct) }

func (s RoomUpdates_List) String() string {
	str, _ := text.MarshalList(0xfb039068971e1e29, s.List)
	return str
}

// RoomUpdates_Promise is a wrapper for a RoomUpdates promised by a client call.
type RoomUpdates_Promise struct{ *capnp.Pipeline }

func (p RoomUpdates_Promise) Struct() (RoomUpdates, error) {
	s, err := p.Pipeline.Struct()
	return RoomUpdates{s}, err
}

type RoomUpdates_RoomUpdate struct{ capnp.Struct }

// RoomUpdates_RoomUpdate_TypeID is the unique identifier for the type RoomUpdates_RoomUpdate.
const RoomUpdates_RoomUpdate_TypeID = 0xdfc61234b2b8d887

func NewRoomUpdates_RoomUpdate(s *capnp.Segment) (RoomUpdates_RoomUpdate, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return RoomUpdates_RoomUpdate{st}, err
}

func NewRootRoomUpdates_RoomUpdate(s *capnp.Segment) (RoomUpdates_RoomUpdate, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return RoomUpdates_RoomUpdate{st}, err
}

func ReadRootRoomUpdates_RoomUpdate(msg *capnp.Message) (RoomUpdates_RoomUpdate, error) {
	root, err := msg.RootPtr()
	return RoomUpdates_RoomUpdate{root.Struct()}, err
}

func (s RoomUpdates_RoomUpdate) String() string {
	str, _ := text.Marshal(0xdfc61234b2b8d887, s.Struct)
	return str
}

func (s RoomUpdates_RoomUpdate) Type() RoomUpdates_RoomUpdate_UpdateType {
	return RoomUpdates_RoomUpdate_UpdateType(s.Struct.Uint16(0))
}

func (s RoomUpdates_RoomUpdate) SetType(v RoomUpdates_RoomUpdate_UpdateType) {
	s.Struct.SetUint16(0, uint16(v))
}

func (s RoomUpdates_RoomUpdate) Source() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s RoomUpdates_RoomUpdate) HasSource() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s RoomUpdates_RoomUpdate) SourceBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s RoomUpdates_RoomUpdate) SetSource(v string) error {
	return s.Struct.SetText(0, v)
}

func (s RoomUpdates_RoomUpdate) SubscriptionId() (string, error) {
	p, err := s.Struct.Ptr(1)
	return p.Text(), err
}

func (s RoomUpdates_RoomUpdate) HasSubscriptionId() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s RoomUpdates_RoomUpdate) SubscriptionIdBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return p.TextBytes(), err
}

func (s RoomUpdates_RoomUpdate) SetSubscriptionId(v string) error {
	return s.Struct.SetText(1, v)
}

func (s RoomUpdates_RoomUpdate) Facts() (RoomUpdates_RoomUpdate_Fact_List, error) {
	p, err := s.Struct.Ptr(2)
	return RoomUpdates_RoomUpdate_Fact_List{List: p.List()}, err
}

func (s RoomUpdates_RoomUpdate) HasFacts() bool {
	p, err := s.Struct.Ptr(2)
	return p.IsValid() || err != nil
}

func (s RoomUpdates_RoomUpdate) SetFacts(v RoomUpdates_RoomUpdate_Fact_List) error {
	return s.Struct.SetPtr(2, v.List.ToPtr())
}

// NewFacts sets the facts field to a newly
// allocated RoomUpdates_RoomUpdate_Fact_List, preferring placement in s's segment.
func (s RoomUpdates_RoomUpdate) NewFacts(n int32) (RoomUpdates_RoomUpdate_Fact_List, error) {
	l, err := NewRoomUpdates_RoomUpdate_Fact_List(s.Struct.Segment(), n)
	if err != nil {
		return RoomUpdates_RoomUpdate_Fact_List{}, err
	}
	err = s.Struct.SetPtr(2, l.List.ToPtr())
	return l, err
}

// RoomUpdates_RoomUpdate_List is a list of RoomUpdates_RoomUpdate.
type RoomUpdates_RoomUpdate_List struct{ capnp.List }

// NewRoomUpdates_RoomUpdate creates a new list of RoomUpdates_RoomUpdate.
func NewRoomUpdates_RoomUpdate_List(s *capnp.Segment, sz int32) (RoomUpdates_RoomUpdate_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return RoomUpdates_RoomUpdate_List{l}, err
}

func (s RoomUpdates_RoomUpdate_List) At(i int) RoomUpdates_RoomUpdate {
	return RoomUpdates_RoomUpdate{s.List.Struct(i)}
}

func (s RoomUpdates_RoomUpdate_List) Set(i int, v RoomUpdates_RoomUpdate) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s RoomUpdates_RoomUpdate_List) String() string {
	str, _ := text.MarshalList(0xdfc61234b2b8d887, s.List)
	return str
}

// RoomUpdates_RoomUpdate_Promise is a wrapper for a RoomUpdates_RoomUpdate promised by a client call.
type RoomUpdates_RoomUpdate_Promise struct{ *capnp.Pipeline }

func (p RoomUpdates_RoomUpdate_Promise) Struct() (RoomUpdates_RoomUpdate, error) {
	s, err := p.Pipeline.Struct()
	return RoomUpdates_RoomUpdate{s}, err
}

type RoomUpdates_RoomUpdate_UpdateType uint16

// RoomUpdates_RoomUpdate_UpdateType_TypeID is the unique identifier for the type RoomUpdates_RoomUpdate_UpdateType.
const RoomUpdates_RoomUpdate_UpdateType_TypeID = 0x8e2ff7d2ea89e179

// Values of RoomUpdates_RoomUpdate_UpdateType.
const (
	RoomUpdates_RoomUpdate_UpdateType_ping              RoomUpdates_RoomUpdate_UpdateType = 0
	RoomUpdates_RoomUpdate_UpdateType_claim             RoomUpdates_RoomUpdate_UpdateType = 1
	RoomUpdates_RoomUpdate_UpdateType_retract           RoomUpdates_RoomUpdate_UpdateType = 2
	RoomUpdates_RoomUpdate_UpdateType_subscribe         RoomUpdates_RoomUpdate_UpdateType = 3
	RoomUpdates_RoomUpdate_UpdateType_death             RoomUpdates_RoomUpdate_UpdateType = 4
	RoomUpdates_RoomUpdate_UpdateType_subscriptionDeath RoomUpdates_RoomUpdate_UpdateType = 5
)

// String returns the enum's constant name.
func (c RoomUpdates_RoomUpdate_UpdateType) String() string {
	switch c {
	case RoomUpdates_RoomUpdate_UpdateType_ping:
		return "ping"
	case RoomUpdates_RoomUpdate_UpdateType_claim:
		return "claim"
	case RoomUpdates_RoomUpdate_UpdateType_retract:
		return "retract"
	case RoomUpdates_RoomUpdate_UpdateType_subscribe:
		return "subscribe"
	case RoomUpdates_RoomUpdate_UpdateType_death:
		return "death"
	case RoomUpdates_RoomUpdate_UpdateType_subscriptionDeath:
		return "subscriptionDeath"

	default:
		return ""
	}
}

// RoomUpdates_RoomUpdate_UpdateTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func RoomUpdates_RoomUpdate_UpdateTypeFromString(c string) RoomUpdates_RoomUpdate_UpdateType {
	switch c {
	case "ping":
		return RoomUpdates_RoomUpdate_UpdateType_ping
	case "claim":
		return RoomUpdates_RoomUpdate_UpdateType_claim
	case "retract":
		return RoomUpdates_RoomUpdate_UpdateType_retract
	case "subscribe":
		return RoomUpdates_RoomUpdate_UpdateType_subscribe
	case "death":
		return RoomUpdates_RoomUpdate_UpdateType_death
	case "subscriptionDeath":
		return RoomUpdates_RoomUpdate_UpdateType_subscriptionDeath

	default:
		return 0
	}
}

type RoomUpdates_RoomUpdate_UpdateType_List struct{ capnp.List }

func NewRoomUpdates_RoomUpdate_UpdateType_List(s *capnp.Segment, sz int32) (RoomUpdates_RoomUpdate_UpdateType_List, error) {
	l, err := capnp.NewUInt16List(s, sz)
	return RoomUpdates_RoomUpdate_UpdateType_List{l.List}, err
}

func (l RoomUpdates_RoomUpdate_UpdateType_List) At(i int) RoomUpdates_RoomUpdate_UpdateType {
	ul := capnp.UInt16List{List: l.List}
	return RoomUpdates_RoomUpdate_UpdateType(ul.At(i))
}

func (l RoomUpdates_RoomUpdate_UpdateType_List) Set(i int, v RoomUpdates_RoomUpdate_UpdateType) {
	ul := capnp.UInt16List{List: l.List}
	ul.Set(i, uint16(v))
}

type RoomUpdates_RoomUpdate_Fact struct{ capnp.Struct }

// RoomUpdates_RoomUpdate_Fact_TypeID is the unique identifier for the type RoomUpdates_RoomUpdate_Fact.
const RoomUpdates_RoomUpdate_Fact_TypeID = 0xbb307c4e25637342

func NewRoomUpdates_RoomUpdate_Fact(s *capnp.Segment) (RoomUpdates_RoomUpdate_Fact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RoomUpdates_RoomUpdate_Fact{st}, err
}

func NewRootRoomUpdates_RoomUpdate_Fact(s *capnp.Segment) (RoomUpdates_RoomUpdate_Fact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RoomUpdates_RoomUpdate_Fact{st}, err
}

func ReadRootRoomUpdates_RoomUpdate_Fact(msg *capnp.Message) (RoomUpdates_RoomUpdate_Fact, error) {
	root, err := msg.RootPtr()
	return RoomUpdates_RoomUpdate_Fact{root.Struct()}, err
}

func (s RoomUpdates_RoomUpdate_Fact) String() string {
	str, _ := text.Marshal(0xbb307c4e25637342, s.Struct)
	return str
}

func (s RoomUpdates_RoomUpdate_Fact) Type() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s RoomUpdates_RoomUpdate_Fact) HasType() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s RoomUpdates_RoomUpdate_Fact) TypeBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s RoomUpdates_RoomUpdate_Fact) SetType(v string) error {
	return s.Struct.SetText(0, v)
}

func (s RoomUpdates_RoomUpdate_Fact) Value() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return []byte(p.Data()), err
}

func (s RoomUpdates_RoomUpdate_Fact) HasValue() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s RoomUpdates_RoomUpdate_Fact) SetValue(v []byte) error {
	return s.Struct.SetData(1, v)
}

// RoomUpdates_RoomUpdate_Fact_List is a list of RoomUpdates_RoomUpdate_Fact.
type RoomUpdates_RoomUpdate_Fact_List struct{ capnp.List }

// NewRoomUpdates_RoomUpdate_Fact creates a new list of RoomUpdates_RoomUpdate_Fact.
func NewRoomUpdates_RoomUpdate_Fact_List(s *capnp.Segment, sz int32) (RoomUpdates_RoomUpdate_Fact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return RoomUpdates_RoomUpdate_Fact_List{l}, err
}

func (s RoomUpdates_RoomUpdate_Fact_List) At(i int) RoomUpdates_RoomUpdate_Fact {
	return RoomUpdates_RoomUpdate_Fact{s.List.Struct(i)}
}

func (s RoomUpdates_RoomUpdate_Fact_List) Set(i int, v RoomUpdates_RoomUpdate_Fact) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s RoomUpdates_RoomUpdate_Fact_List) String() string {
	str, _ := text.MarshalList(0xbb307c4e25637342, s.List)
	return str
}

// RoomUpdates_RoomUpdate_Fact_Promise is a wrapper for a RoomUpdates_RoomUpdate_Fact promised by a client call.
type RoomUpdates_RoomUpdate_Fact_Promise struct{ *capnp.Pipeline }

func (p RoomUpdates_RoomUpdate_Fact_Promise) Struct() (RoomUpdates_RoomUpdate_Fact, error) {
	s, err := p.Pipeline.Struct()
	return RoomUpdates_RoomUpdate_Fact{s}, err
}

const schema_92bf88982dabc9c9 = "x\xda\x8c\x93\xbfk\x14A\x1c\xc5\xdf\x9b\xb95\x09$" +
	"n&\x1bP\x8b$\x16\x09\xe6\x02\x89\xf9ea\x9a\x98" +
	"C\x844\x92\x09\xda\x04\x05'{\xa3wr\xc9\xae\xb7" +
	"s\xca\x89\x90\xd2\xd8\x88\xa4\x89\xf8/\x88\x8d\x95 \"" +
	"6JZ+;\xb1\x12\xf2\x0fXX\xac\xec\x85\xdb[" +
	"l\xb4\xda\xe5\xcd\x97\x9d\xcf\xfb\xcc\xce\xfc\x08\xaf\x88\x05" +
	"\xef\x8b\x00\xf4y\xefT\xda\xfe\xf1\xec\xf8\xeb\xaf\x8b\xcf" +
	"\xa1\xa6E\xfa\xf4\xdb\xbb\xb7\xcb#\x9f\xbf\x03\\Z\xe7" +
	"+\x06\x86}@p\x9b\x87`ZI\xc2\xa9\xebO\xe6" +
	"\xdfCM\xb37\xe9\x89>`\xe9\x0d\xef3\xf8\xd4\x19" +
	"\xfe\xc0G(\xac\xeb12-\x8f\x8f\x1f\xd6^\xc8\xdf" +
	"\xf0d6}NT\x18\x94\xc5\x05 X\x13?QX" +
	"W\x8a\xe9\xd1\xd1\xeb\xd9\x97\xfb\x1f\x0f\xe0u\xbeW\x96" +
	"\xc7\xc1%y&\x9b\x95\xab\x98M\x9bQ\xb4\xd3\x8a\xab" +
	"\xc6sv.4\xf1n\xbc\xb2\x19E;7\xe3\xaaq" +
	"6\x99\xeb\xbd\xcf\x9d<n\xb4el7H}\x96\x02" +
	"Pk3\x00\xa9./\x02\x14j\xa1\x02P\xaa\xf2&" +
	"\xc0\x92\x9a\xcaBO\x8d\x1d\x00~\\\xdf\xbd7\x116" +
	"L}g\xafi]\xd3\x84.MZ\xdbI\xd8\xaco" +
	"\x83v\xa2j\x8d\xabu\x93\x98\xae\x1e\xed^\xb5\xc6\xb1" +
	"\x96\xe3\x95\xfe\x85\xe7_3\xa1\xcb\xc0\xfae\x09(\x11" +
	"P\xe5\x19@OJ\xeayAE\x8e2\x0bg\x17\x01" +
	"=-\xa9\x97\x05}\xd7\x8e-\x07!8\x08N<4" +
	"\x8d\x96\xe5\x10\x04\x87\xc0\xff\xde\x18\xba\x9f,\x1c\xfb\xc0" +
	"V\xe1d\x07f\xd2\xae6\xc8\xd8v\x18\xf5p\x0eh" +
	"2\xc0[\x92\xba&\xd8\xe5\xb3+\x80\xbe#\xa9\x1b\x82" +
	"Jp\xb4\xa3\xb9\xfe\x18\xd05I\xed\x04\x95\x14\xa3\x94" +
	"\x80z\x905iH\xea\xfdn\x13\xbf\xc7\x01\xd2\x07W" +
	"\x93\xa8\xd5\x0c\xf3\x8a\xb9a\xacf\x8a\xd7\xaby\xf7\xbb" +
	"&t\x09O\x83\x1b\x92\x1c\xee5\x00\xb30\x97!\xfe" +
	"\x96\xe1g6t\x89\x85?Tq+\xed\xea\x81tV" +
	"\x97\xf2\xbeC\x15@\xf7K\xeaI\xc1\xbd\xd6\x89\xca\xde" +
	"\xa6\x85\xdb\x92\x85\x7f\x02\x00\x00\xff\xff5\\\xe7\xf1"

func init() {
	schemas.Register(schema_92bf88982dabc9c9,
		0x8e2ff7d2ea89e179,
		0xbb307c4e25637342,
		0xdfc61234b2b8d887,
		0xfb039068971e1e29)
}
