// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package roomupdatefbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Fact struct {
	_tab flatbuffers.Table
}

func GetRootAsFact(buf []byte, offset flatbuffers.UOffsetT) *Fact {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Fact{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Fact) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Fact) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Fact) Type() FactType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return FactType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Fact) MutateType(n FactType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Fact) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Fact) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Fact) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Fact) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func FactStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FactAddType(builder *flatbuffers.Builder, type_ FactType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func FactAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func FactStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FactEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
