// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package roomupdatefbs

import "strconv"

type FactType int8

const (
	FactTypeId      FactType = 0
	FactTypeText    FactType = 1
	FactTypeInteger FactType = 2
	FactTypeFloat   FactType = 3
	FactTypeBinary  FactType = 4
)

var EnumNamesFactType = map[FactType]string{
	FactTypeId:      "Id",
	FactTypeText:    "Text",
	FactTypeInteger: "Integer",
	FactTypeFloat:   "Float",
	FactTypeBinary:  "Binary",
}

var EnumValuesFactType = map[string]FactType{
	"Id":      FactTypeId,
	"Text":    FactTypeText,
	"Integer": FactTypeInteger,
	"Float":   FactTypeFloat,
	"Binary":  FactTypeBinary,
}

func (v FactType) String() string {
	if s, ok := EnumNamesFactType[v]; ok {
		return s
	}
	return "FactType(" + strconv.FormatInt(int64(v), 10) + ")"
}
