// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package roomupdatefbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResultSet struct {
	_tab flatbuffers.Table
}

func GetRootAsResultSet(buf []byte, offset flatbuffers.UOffsetT) *ResultSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResultSet{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ResultSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResultSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResultSet) ResultSet(obj *RoomResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ResultSet) ResultSetLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ResultSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ResultSetAddResultSet(builder *flatbuffers.Builder, resultSet flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(resultSet), 0)
}
func ResultSetStartResultSetVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ResultSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
